#!/usr/bin/env bash

DIR=$(python -c 'import os, sys; print os.path.realpath(os.getcwd())')

docker build . -t clarabridge/golang-dev
docker run -it -v $DIR:/workspace -w /workspace clarabridge/golang-dev

